### PR TITLE
fix(demo): improve cms-text-element

### LINKED ISSUE #275: [BUG]  CmsElementText component does not work with CMS text styles
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CmsElementText component from cms-base package does not work with CMS builder text block styles (text color/size, tables, ordered/unordered lists, etc):

In CMS builder:
Screenshot from 2023-06-20 11-05-58

In Frontends:
Screenshot from 2023-06-20 11-07-44

### Expected Behavior

CMS Text block styles should be rendered in Frontends so that shop owners could modify text styles from admin side.

### Steps To Reproduce

1. Create Text block in Shopping Experiances page in Shopware admin
2. Add styles to Text block
3. Check page in Frontends.

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrocksiNet**
### Description
closes #275

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### Screenshots (if applicable)

**Before:**
grafik

**After:**
grafik

### Additional context
- Added possibilities to support colors from admin and align
- SSR: Still shows style="" and class="" after hard reload (did not find the root of that)
- CSR: HTML is mostly clean without empty style and class
- Config for UnoCSS is moved to a own config file because suggest by docu
- Added some base styles as preflights as example (and we miss them in demo store)

### CODE REVIEW

File: packages/cms-base/components/public/cms/element/CmsElementText.vue [hunk 1]
```diff
@@ -72,6 +72,30 @@ const CmsTextRender = () => {
...
+        conditions(node: any) {
+          return node.type === "tag" && node.name === "font";
+        },
+        renderer(node: any, children: any, createElement: any) {
+          // convert from <font color="#ce0000">Headline 1</font> to <span style="color:#ce0000">Headline 1</span>
+          let newStyle = null;
+          const styleColor = node.attrs?.color ?? null;
+          if (styleColor) {
+            const currentStyle = node.attrs?.style ?? "";
+            newStyle = "color:" + styleColor + ";" + currentStyle;
```
Comment (mdanilowicz) [inline packages/cms-base/components/public/cms/element/CmsElementText.vue:85]:
```suggestion
            newStyle = `color:${styleColor};${currentStyle}`;
```

File: packages/cms-base/components/public/cms/element/CmsElementText.vue [hunk 2]
```diff
@@ -72,6 +72,30 @@ const CmsTextRender = () => {
...
         },
       },
+      font: {
+        conditions(node: any) {
+          return node.type === "tag" && node.name === "font";
+        },
+        renderer(node: any, children: any, createElement: any) {
+          // convert from <font color="#ce0000">Headline 1</font> to <span style="color:#ce0000">Headline 1</span>
+          let newStyle = null;
+          const styleColor = node.attrs?.color ?? null;
```
Comment (mdanilowicz) [inline packages/cms-base/components/public/cms/element/CmsElementText.vue:82]:
```suggestion
          const styleColor = node?.attrs?.color;
```

File: packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts [hunk 3]
```diff
@@ -1,15 +1,41 @@
...
+    align = node.attrs.align;
+    delete node.attrs.align;
+  }
+
+  const { ...rest } = node.attrs;
+  let attrs = rest;
+
+  if (Object.keys(rest).length === 0) {
+    attrs = null;
+  }
```
Comment (mdanilowicz) [inline packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts:33]:
```suggestion
const attrs = (Object.keys(node.attrs).length === 0)? null : {...node.attrs}
```
It should work like that :D But please test if you decide to use this one line :)

**Review by mdanilowicz — APPROVED** [review]

File: packages/cms-base/components/public/cms/element/CmsElementText.vue [hunk 4]
```diff
@@ -72,6 +72,30 @@ const CmsTextRender = () => {
           );
         },
       },
+      font: {
+        conditions(node: any) {
```
Comment (patzick) [inline packages/cms-base/components/public/cms/element/CmsElementText.vue:76]: let's type it properly instead of `any`, here and in other places :)

File: packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts [hunk 5]
```diff
@@ -1,15 +1,41 @@
 type Options = {
-  style: String;
-  class: String;
-  attrs: Object;
+  align: String | null;
+  attrs: Object | null;
+  class: String | null;
+  style: String | null;
```
Comment (patzick) [inline packages/cms-base/helpers/html-to-vue/getOptionsFromNode.ts:5]:
```suggestion
  align?: string;
  attrs?: Record<string, string>;
  class?: string;
  style?: string;
```
wouldn't be better to have it as undefined if not existing?

**Review by patzick — CHANGES_REQUESTED** [review]

**Comment by BrocksiNet** [comment]
I did my best to add your suggestions. :muscle: 
Thx for your feedback guys. :heart_decoration:
