### PR TITLE
fix(composables): add shipping costs

### LINKED ISSUE #1576: [BUG] No shipping promotion displayed on the cart summary
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Community issue https://shopwarecommunity.slack.com/archives/C050L6NCMGQ/p1736433041633699

The goal is to display all shipping entries, also the promotions

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mdanilowicz**
### Description

This pull request fixes display shipping costs in the cart and checkout components. The changes include adding a `shippingCosts` property to the `useCart` composable, updating the cart and checkout components to display this information, and adding corresponding tests and translations.

Screenshot 2025-01-14 at 10 19 01

### Feature Implementation:

* [`packages/composables/src/useCart/useCart.ts`](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R69-R76): Added `shippingCosts` property to `UseCartReturn` type and implemented the logic to compute shipping costs. [[1]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R69-R76) [[2]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R248-R251) [[3]](diffhunk://#diff-62200ee55ed613e59b385b7ec684bf93fc968a1b9e225cd5874c6f24ec7e73f3R310)
* [`packages/composables/src/useCart/useCart.test.ts`](diffhunk://#diff-b2cd481f495a6152f73d8b6733e28479c474dad27287a5055c4965a9bc08f419R218-R250): Added tests to verify the `shippingCosts` property returns correct values.

### Component Updates:

* [`templates/vue-demo-store/pages/checkout/cart.vue`](diffhunk://#diff-6dcbeb37ca8d7cf09df43ac9b5ce22b06713b3382efc8beda4bc272e4cf1f226L7-R7): Updated to use `shippingCosts` and display each shipping cost in the cart view. [[1]](diffhunk://#diff-6dcbeb37ca8d7cf09df43ac9b5ce22b06713b3382efc8beda4bc272e4cf1f226L7-R7) [[2]](diffhunk://#diff-6dcbeb37ca8d7cf09df43ac9b5ce22b06713b3382efc8beda4bc272e4cf1f226R47-R65)
* [`templates/vue-demo-store/pages/checkout/index.vue`](diffhunk://#diff-0bfd10dfff54f08afcd8826405c7a5172141e848d4577f7c308899e258661a1fL48-R48): Updated to use `shippingCosts` and display each shipping cost in the checkout view. [[1]](diffhunk://#diff-0bfd10dfff54f08afcd8826405c7a5172141e848d4577f7c308899e258661a1fL48-R48) [[2]](diffhunk://#diff-0bfd10dfff54f08afcd8826405c7a5172141e848d4577f7c308899e258661a1fR1017-R1034) [[3]](diffhunk://#diff-0bfd10dfff54f08afcd8826405c7a5172141e848d4577f7c308899e258661a1fL1025-R1043)

### Translations:

* [`templates/vue-demo-store/i18n/de-DE/cart.json`](diffhunk://#diff-30d00b0a27f9ac88f89730e37782872133cf451da7126b6f2f3bea5b72f53d8aR11): Added translation for "shipping costs."
* [`templates/vue-demo-store/i18n/en-GB/cart.json`](diffhunk://#diff-706428de9af97cbc0e3736a6b8c15add006526c30459639c15b70b2858e6d9eeR11): Added translation for "shipping costs."
* [`templates/vue-demo-store/i18n/pl-PL/cart.json`](diffhunk://#diff-76bb910993a39503d551209be40aedc1d784f29cd8716a4a33eb4519f9c4b431R11): Added translation for "shipping costs."

 closes #1576

### CODE REVIEW

File: packages/composables/src/useCart/useCart.ts [hunk 1]
```diff
@@ -66,8 +66,14 @@ export type UseCartReturn = {
   totalPrice: ComputedRef<number>;
   /**
    * Shipping price
+   *
+   * @deprecated Use `shippingTotal` instead
```
Comment (patzick) [inline packages/composables/src/useCart/useCart.ts:70]: looks like this is in the wrong line? You say to use the thing which becomes deprecated ;)

File: .changeset/calm-ligers-give.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@shopware-pwa/composables-next": patch
+---
+
+Added `shippingCosts` property in `useCart` composable that returns shipping costs of the cart, with the shipping discounts
```
Comment (patzick) [inline .changeset/calm-ligers-give.md:5]: no info about the deprecation

**Review by patzick — CHANGES_REQUESTED** [review]
just one thing to clarify deprecation

File: packages/composables/src/useCart/useCart.ts (hunk 1 above)
Comment (mdanilowicz) [reply packages/composables/src/useCart/useCart.ts:70]: ups :D fixed

File: .changeset/calm-ligers-give.md (hunk 2 above)
Comment (mdanilowicz) [reply .changeset/calm-ligers-give.md]: done

**Review by patzick — APPROVED** [review]

File: templates/vue-demo-store/pages/checkout/index.vue [hunk 3]
```diff
@@ -1022,7 +1040,7 @@ const beforeCreateOrderValidation = () => {
                 class="text-secondary-900 font-medium"
                 data-testid="cart-subtotal"
               />
-            </div>
+            </div> -->
```
Comment (BrocksiNet) [inline templates/vue-demo-store/pages/checkout/index.vue:1043]: why do we not remove it?
