### PR TITLE
fix(demo): do not execute watch if 0

### LINKED ISSUE #457: [BUG] Params (min-price, max-price, order) added to URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking in Top-Navigation and waiting a bit you will get this URL for example:

http://localhost:3000/Cooking-pleasure-Provence/?min-price=3&max-price=350&order=name-asc

Sometimes when you click fast on a product these params are added to the product detail page URL.

We need these params for sorting and filtering but I guess the default params should not be added to the URL.

### Expected Behavior

URL should not change when no filter or sort is set.

Expected URL will look and stay like this:
http://localhost:3000/Cooking-pleasure-Provence/The expected

### Steps To Reproduce

1. Click some Link from Top-Navigation
2. Wait until the params are added to the URL

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BrocksiNet**
### Description

closes #457

### Type of change

Bug fix (non-breaking change that fixes an issue)

### Additional context

The watch was also executed with the default value of 0, this we skip now and only change when a real user interaction took place. Also, a max or min price filter with 0 is not something retailers like to filter for so I guess it is safe to skip it in that case.

### CODE REVIEW

File: packages/cms-base/components/listing-filters/SwFilterPrice.vue [hunk 1]
```diff
@@ -57,23 +57,23 @@ const dropdownElement = ref(null);
 onClickOutside(dropdownElement, () => (isFilterVisible.value = false));
 
 function onMinPriceChange(newPrice: number, oldPrice: number) {
-  if (newPrice == oldPrice) return;
+  if (newPrice == oldPrice || oldPrice == 0) return;
```
Comment (patzick) [inline packages/cms-base/components/listing-filters/SwFilterPrice.vue:60]:
```suggestion
  if (newPrice === oldPrice || oldPrice === 0) return;
```

File: packages/cms-base/components/listing-filters/SwFilterPrice.vue [hunk 2]
```diff
@@ -57,23 +57,23 @@ const dropdownElement = ref(null);
...
     value: newPrice,
   });
 }
-const debounceMinPriceUpdate = useDebounceFn(onMinPriceChange, 1000);
+const debounceMinPriceUpdate = useDebounceFn(onMinPriceChange, 500);
 watch(() => prices.min, debounceMinPriceUpdate);
 
 function onMaxPriceChange(newPrice: number, oldPrice: number) {
-  if (newPrice == oldPrice) return;
+  if (newPrice == oldPrice || oldPrice == 0) return;
```
Comment (patzick) [inline packages/cms-base/components/listing-filters/SwFilterPrice.vue:70]:
```suggestion
  if (newPrice === oldPrice || oldPrice === 0) return;
```

File: templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue [hunk 3]
```diff
@@ -47,23 +47,23 @@ const dropdownElement = ref(null);
 onClickOutside(dropdownElement, () => (isFilterVisible.value = false));
 
 function onMinPriceChange(newPrice: number, oldPrice: number) {
-  if (newPrice == oldPrice) return;
+  if (newPrice == oldPrice || oldPrice == 0) return;
```
Comment (patzick) [inline templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue:50]:
```suggestion
  if (newPrice === oldPrice || oldPrice === 0) return;
```

File: templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue [hunk 4]
```diff
@@ -47,23 +47,23 @@ const dropdownElement = ref(null);
...
     value: newPrice,
   });
 }
-const debounceMinPriceUpdate = useDebounceFn(onMinPriceChange, 1000);
+const debounceMinPriceUpdate = useDebounceFn(onMinPriceChange, 500);
 watch(() => prices.min, debounceMinPriceUpdate);
 
 function onMaxPriceChange(newPrice: number, oldPrice: number) {
-  if (newPrice == oldPrice) return;
+  if (newPrice == oldPrice || oldPrice == 0) return;
```
Comment (patzick) [inline templates/vue-demo-store/components/listing-filters/ListingFiltersPrice.vue:60]:
```suggestion
  if (newPrice === oldPrice || oldPrice === 0) return;
```

**Review by patzick — APPROVED** [review]
